name: Feature Request
description: Request new features here.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to see added to the game?
    validations:
      required: true