name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Restore Previous Cache
        id: cache-build-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/debug/linux/haxe/
            export/debug/linux/obj/
          key: cache-linux-debug

      - name: Installing Libraries
        run: haxe --interp -cp ./actions/libs-installer -D analyzer-optimize -main Main
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build linux -debug

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: await require('./actions/cache/clear-cache.js')({github, context}, 'cache-linux-debug');

      - name: Save Current Cache
        uses: actions/cache@main
        with:
          key: cache-linux-debug
          path: |
            .haxelib/
            export/debug/linux/haxe/
            export/debug/linux/obj/
          restore-keys: |
            cache-linux-debug

      - name: Tar files
        run: tar -zcvf Rhythmo.tar.gz export/debug/linux/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: Rhythmo.tar.gz
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Restore Previous Cache
        id: cache-build-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/debug/windows/haxe/
            export/debug/windows/obj/
          key: cache-windows-debug

      - name: Set Cache Status
        id: cache-status
        run: echo CACHE_HIT=${{ steps.cache-build-restore.outputs.cache-hit }} | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: powershell

      - name: Installing Libraries
        run: haxe --interp -cp ./actions/libs-installer -D analyzer-optimize -main Main
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows -debug

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: await require('./actions/cache/clear-cache.js')({github, context}, 'cache-windows-debug');

      - name: Save Current Cache
        uses: actions/cache@main
        with:
          key: cache-windows-debug
          path: |
            .haxelib/
            export/debug/windows/haxe/
            export/debug/windows/obj/
          restore-keys: |
            cache-windows-debug

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/debug/windows/bin
  buildMac:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Restore Previous Cache
        id: cache-build-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/debug/macos/haxe/
            export/debug/macos/obj/
          key: cache-mac-debug

      - name: Installing Libraries
        run: haxe --interp -cp ./actions/libs-installer -D analyzer-optimize -main Main
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build mac -debug

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: await require('./actions/cache/clear-cache.js')({github, context}, 'cache-mac-debug');

      - name: Save Current Cache
        uses: actions/cache@main
        with:
          key: cache-mac-debug
          path: |
            .haxelib/
            export/debug/macos/haxe/
            export/debug/macos/obj/
          restore-keys: |
            cache-mac-debug

      - name: Tar files
        run: tar -zcvf Rhythmo.tar.gz export/debug/macos/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: Rhythmo.tar.gz